{**********************************************************************}
{                                                                      }
{                 This auxiliary unit was generated by                 }
{                 DevExpress Project Settings Manager.                 }
{                                                                      }
{  The dxSettings unit reflects the current project settings in        }
{  the source code of your project. Do not modify this file directly.  }
{                                                                      }
{  Use the DevExpress Project Settings dialog to configure all project }
{  settings related to DevExpress components. Select the following     }
{  item in the main menu of your RAD Studio IDE to invoke the dialog:  }
{                                                                      }
{            Project | DevExpress Settings for Your Project            }
{                                                                      }
{**********************************************************************}

unit amTranslationManager.dxSettings;

{$I cxVer.inc}

interface

uses
  Winapi.Windows, System.Classes, Vcl.Themes, dxCore, cxLookAndFeels, dxSkinsCore, dxSkinsForm,
  dxSkinTheBezier, dxSkinBasic;

implementation

procedure LoadAppearanceToRootLookAndFeel(ARoot: TcxRootLookAndFeel);
begin
  ARoot.Kind := lfUltraFlat;
  ARoot.NativeStyle := False;
  ARoot.ScrollbarMode := sbmClassic;
  ARoot.ScrollMode := scmDefault;
  ARoot.SkinName := 'TheBezier';
  ARoot.RenderMode := rmDefault;
  ARoot.TouchMode := False;
  ARoot.FormCorners := fcDefault;
  ARoot.SkinPaletteName := 'Fireball';
  ARoot.ShowFormShadow := bDefault;
  ARoot.UseSkins := True;
  ARoot.UseImageSet := imsDefault;
  ARoot.UseSkinsInPopupMenus := True;
  ARoot.UseGlobalSkin := False;
end;

procedure LoadAppearance;
var
  ARoot: TcxRootLookAndFeel;
begin
{$IFDEF DELPHI120}
  TStyleManager.ChangeChildFormSystemBorder := False;
{$ENDIF}
  cxProjectSettingsAreOverriding := True;
  cxCanUseSkinsWithoutSkinController := True;
  ARoot := TcxRootLookAndFeel.Instance;
  ARoot.BeginUpdate;
  try
    LoadAppearanceToRootLookAndFeel(ARoot);
  finally
    ARoot.EndUpdate;
  end;
  TdxVisualRefinements.LightStyleMode := lsmOnlyBorders;
end;

initialization
  LoadAppearance;
end.